---
name: Tuan Duc Design
title: Tuan Duc Design
subtitle: Specialist site to share knowledge of VPS and Website
description: Specialist page sharing knowledge related to VPS development and Website
  optimization.
cdn: "enabled"
cdn-cloudinary: "https://res.cloudinary.com/td-blog/image/upload/f_auto,q_auto"
cdn-s3:
cdn-netlify:
logo: /static/tuanducdesign.jpg
favicon: /static/tuanducdesign.jpg
apple-touch-icon: /static/tuanducdesign.jpg
apple-touch-icon-57x57: /static/apple-touch-icon-57x57.png
apple-touch-icon-72x72: /static/apple-touch-icon-72x72.png
apple-touch-icon-76x76: /static/apple-touch-icon-76x76.png
apple-touch-icon-114x114: /static/apple-touch-icon-114x114.png
apple-touch-icon-120x120: /static/apple-touch-icon-120x120.png
apple-touch-icon-144x144: /static/apple-touch-icon-144x144.png
apple-touch-icon-152x152: /static/apple-touch-icon-152x152.png
apple-touch-icon-180x180: /static/apple-touch-icon-180x180.png
baseurl: 
url: https://tuanducdesign.com
analytics: "enabled"
google_analytics: G-JLS45PZZXS
disquscmt: "enabled"
disqus: tuanducdesign
facebook:
  app_id: "294587991860787"
  publisher: "https://www.facebook.com/121349286117840"
  admins: "100005485267478"
chat: "enabled"
fanpage-chat: "121349286117840"
permalink: "/:year/:month/:title"
twitter:
  username: tuanducdesign
  card: summary_large_image
social:
  name: Tuan Duc Design
  links:
  - https://twitter.com/tuanducdesign
  - https://www.facebook.com/tuanduc.support
  - https://www.instagram.com/mi.profile.56
  - https://github.com/tuanducdesign
defaults:
- scope:
    path: ''
  values:
    image: "/static/CA0E67E9-AAD0-4D36-82D8-674C7504DFD1.jpg"
timezone: Asia/Ho_Chi_Minh
authors:
  tuanducdesign:
    name: Tuan Duc Design
    username: tuanducdesign
    display_name: Tuan Duc Design
    photo: /static/tuanducdesign.jpg
    email: miumiu.official.56@gmail.com
    web: https://tuanducdesign.com
    facebook: tuanduc.support
    twitter: tuanducdesign
    instagram: mi.profile.56
    description: Ask me about Optimize Website, Install VPS, Hosting Selection...
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-include-cache
jekyll-archives:
  enabled:
  - categories
  layout: archive
  permalinks:
    category: "/category/:name/"
paginate: "9"
paginate_path: "/page/:num/"
markdown: kramdown
highlighter: rouge
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge
#   syntax_highlighter_opts:
#     block:
#       line_numbers: true
adsense: enabled
adsense-data-ad-client: ca-pub-4183134625750063
adsense-data-ad-slot: 5639974067

lazyimages: enabled
sass:
  style: compressed
include:
- ".htaccess"
- _pages
- manifest.json
exclude:
- changelog.md
- LICENSE.txt
- README.md
- Gemfile
- Gemfile.lock
- ".jekyll-cache"
keep_files:
- static
notification_cmt:
  - name: Due to the influence of AAG cables, we temporarily disable commenting until the cable is stable.
top_articles: 
  - url: /2021/01/cai-dat-module-pagespeed-len-may-chu-nginx
    title: Cài đặt Module PageSpeed lên máy chủ Nginx
    category: Server
  - url: /2021/01/huong-dan-su-dung-thu-vien-deferjs-cua-mai-nhut-tan
    title: Hướng Dẫn Sử Dụng Thư Viện DeferJS của Mai Nhựt Tân
    category: Library
  - url: /2021/02/bo-ba-thu-vien-than-thanh-giup-website-toi-uu
    title: Bộ Ba Thư Viện Thần Thánh Giúp Website Tối Ưu
    category: Library
  - url: /2021/04/series-nextdns
    title: Series hướng dẫn sử dụng NextDNS
    category: Series
compress_html:
    clippings: []
    comments: [all]
    endings: []
    ignore:
    envs: [local]
    blanklines: false
    profile: false
    startings: []
