# Site
name: "Tuan Duc Design"
title: "Tuan Duc Design"
subtitle: "Specialist site to share knowledge of VPS and Website"
description: "Specialist page sharing knowledge related to VPS development and Website optimization."
logo: 'static/tuanducdesign.jpg'
favicon: 'static/tuanducdesign.jpg'
baseurl:
url: 'https://tuanducdesign.com'
google_analytics: 'UA-175649416-1'
disqus: 'tuanducdesign'
fanpage-chat: '121349286117840'
include: ["_pages"]
permalink: /:year/:month/:title.html/
twitter:
  username: tuanducdesign
  card: summary_large_image
facebook:
  app_id: 294587991860787
  publisher: 121349286117840
  admins: 100005485267478
social:
  name: Tuan Duc Design
  links:
    - https://twitter.com/tuanducdesign
    - https://www.facebook.com/tuanduc.support
    - https://www.instagram.com/mi.profile.56
    - https://github.com/tuanducdesign
defaults:
  - scope:
      path: ""
    values:
      image: https://cdn.tuanducdesign.com/assets/images/CA0E67E9-AAD0-4D36-82D8-674C7504DFD1.jpg
timezone: Asia/Ho_Chi_Minh
# Authors
authors:
  tuanducdesign:
    name: Tuan Duc Design
    username: tuanducdesign
    display_name: Tuan Duc Design
    photo: https://cdn.tuanducdesign.com/assets/images/tuanducdesign.jpg
    email: miumiu.official.56@gmail.com
    web: https://tuanducdesign.com
    facebook: tuanduc.support
    twitter: tuanducdesign
    instagram: mi.profile.56
    description: "Ask me about Optimize Website, Install VPS, Hosting Selection..."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 5
paginate_path: /page/:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-xxxxxxxxxxxxxxxx"
adsense-data-ad-slot: "xxxxxxxxxx"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

sass:
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

keep_files: [static]

############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true
  
  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/static/media"]

  # Whether to search in nested directories or not
  nested: false

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files 
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: /static/media

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################